### ISSUE TITLE
Using with docker compose

### ISSUE THREAD

**Issue by michaeljs1990** [jenkinsci/docker-ssh-agent#6]
```
 command: |
    "ssh-rsa something"
```

This is the yaml that you have to use if using docker compose with this container. Would be nice if it used an environment variable instead. I would make the change but since i am sure everyone is using master of this image you would now have to support both ways making the startup script pretty messy.

**Comment by ydubreuil** [comment]
Very good idea! I just proposed a PR for this: https://github.com/jenkinsci/docker-ssh-slave/pull/7

**Comment by mgrzechocinski** [comment]
I found another workaround, using docker-compose's [`env_file`](https://docs.docker.com/compose/environment-variables/):

```
$ cat slave.env
JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAC[...] jenkins@macmini
```
(note lack od `""` in env variable)

Then i `docker-compose.yaml`:
```
slave-test-1:
    container_name: slave-test-1-container
    restart: always
    image: jenkins/ssh-slave
    env_file:
      - slave.env
```
Slave accepts connections with matching private key:
```
slave-test-1-container     | Accepted publickey for jenkins from 172.21.0.11 port 42030 ssh2: RSA SHA256:3Jv23vZ+VdaZJ0N/bi+GMcevDSHli3kyX0Rbg10kVV8
```
