### ISSUE TITLE
Main controller and ssh-agent on same host

### ISSUE THREAD

**Issue by bzgec** [jenkinsci/docker-ssh-agent#76]
I am trying to setup [jenkins/jenkins](https://hub.docker.com/r/jenkins/jenkins) (main controller) and [jenkins/ssh-agent](https://hub.docker.com/r/jenkins/ssh-agent) on the same host with docker. 
I have no problem with running jobs on main controller with built-in node. 

But I can't figure out how to setup ssh-agent correctly. 

Below is my setup.
```
docker-compose.yml
--------------------------------------------------------------------
  jenkins-agent:
    container_name: jenkins-agent
    restart: unless-stopped
    build:
      context: ./jenkins-agent
      dockerfile: Dockerfile
    ports:
      - 222:22
    depends_on:
      - jenkins-master
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./jenkins-agent/.env.dev
```
```
jenkins-agent/Dockerfile
--------------------------------------------------------------------
FROM jenkins/ssh-agent:3.0.0-alpine
```
```
jenkins-agent/.env.dev
--------------------------------------------------------------------
JENKINS_AGENT_SSH_PUBKEY=ssh-rsa ...
```

I tried to connect to it with ssh from terminal but no luck. SSH key should be OK.
![image](https://user-images.githubusercontent.com/34318921/121385840-c16eed00-c949-11eb-9756-68d7112db6cb.png)
![image](https://user-images.githubusercontent.com/34318921/121385861-c6cc3780-c949-11eb-90a7-fed5ae292d5e.png)
![image](https://user-images.githubusercontent.com/34318921/121386052-f54a1280-c949-11eb-9d69-2c11676dbcf2.png)
![image](https://user-images.githubusercontent.com/34318921/121385896-d0ee3600-c949-11eb-8f7c-98fb4364c528.png)
![image](https://user-images.githubusercontent.com/34318921/121385951-e2374280-c949-11eb-96c3-8ce69c8cf2a5.png)

I don't know if I am missing something simple, but I am kind of stuck. 

Any help would be appreciated. 
Thanks
